### ISSUE TITLE
@dpr DataFrame vs @dpr CSV.File

### ISSUE THREAD

**Issue by accopeland** [ronisbr/TerminalPager.jl#17]
Thanks for this long needed feature.  

Probably it is my expectations that are at fault here, but I expected to find that if docs were available via 'help?>' then I should be able to swap 'help?>' for '@dpr'.  Specifically,

?help> DataFrames   # output as expected
@dpr DataFrames      # paged as expected

?help> CSV.File          # output as expected
However,
```
julia> @dpr CSV.File 
ERROR: UndefVarError: CSV not defined
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/TerminalPager/QD9o8/src/helpers.jl:25
````

@v1.6) pkg> st TerminalPager
      Status `~/.julia/environments/v1.6/Project.toml`
  [0c614874] TerminalPager v0.2.1

Julia Version 1.6.0
Commit f9720dc2eb (2021-03-24 12:55 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)

**Comment by ronisbr** [comment]
Hi @accopeland 

Thanks! I think it was a problem in an escaping inside the macro. Can you please test against `main`?

By the way, we changed `@dpr` to `@help`.

**Comment by accopeland** [comment]
Works perfectly, thanks.

Checked with
]
***@***.***) pkg> add TerminalPager#acfd854
***@***.***) pkg> st TerminalPager
  Status `~/.julia/environments/v1.6/Project.toml`
  [0c614874] TerminalPager v0.2.1 `
https://github.com/ronisbr/TerminalPager.jl.git#acfd854`

julia> using TerminalPager
julia> @help CSV.Filie
