### ISSUE TITLE
Possible to Tag a New Release

### ISSUE THREAD

**Issue by TheCedarPrince** [ronisbr/TerminalPager.jl#19]
Hey @ronisbr !

Would it be possible to tag a new release soon?
Currently, the release does not allow one to do:

```julia
julia> @help Module.function
```

to get the docstrings and returns the error seen in: #17 
Thanks!

**Comment by ronisbr** [comment]
Oops, sorry! I forgot :)

I will do this as soon as I arrive home (probably tomorrow).

**Comment by TheCedarPrince** [comment]
Great!
You're the best! :D

**Comment by ronisbr** [comment]
Done! Please, let me know if everything is working fine :)

**Comment by TheCedarPrince** [comment]
Works perfectly! 
Thank you @ronisbr :)

**Comment by ronisbr** [comment]
Awesome! Sorry for the delay :)

**Comment by TheCedarPrince** [comment]
Haha, no need to apologize - thank you for maintaining this package!
