### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by GregPlowman** [ronisbr/TerminalPager.jl#20]
I notice that compat has been updated for latest `StringManipulation`, but has not been released.
Is it worthwhile to release a new version?

**Comment by ronisbr** [comment]
Perfect! I will do this!

**Comment by ronisbr** [comment]
Hi @GregPlowman,

Sorry, I completely forgot! I will do this as soon as possible.

**Comment by ronisbr** [comment]
Done! Should be available soon. I am really sorry for the delay.

**Comment by GregPlowman** [comment]
Thanks!
