### ISSUE TITLE
Enter key to move down

### ISSUE THREAD

**Issue by carstenbauer** [ronisbr/TerminalPager.jl#23]
With `less` (and partners) one can use the enter key to move down. I realize that I can achieve this with

```julia
TerminalPager.set_keybinding("<enter>", :down)
```

but I would vote for having this as an (additional) default. What do you think?

**Comment by ronisbr** [comment]
Hi @carstenbauer !

I have no opinion on this! However, if `less` uses this as default, I think we should also use it here.
