### ISSUE TITLE
fastdown only shifts by 1 line

### ISSUE THREAD

**Issue by bjarthur** [ronisbr/TerminalPager.jl#35]
on both mac and linux.  so it behaves just the same as regular down.  similarly for fastup.  fast{left,right} work as documented.  this is on julia v1.10 and TerminalPager v0.5.1.

**Comment by ronisbr** [comment]
Hi @bjarthur 

I cannot reproduce this bug. When I hit `SHIFT + DOWN` or `SHIFT + UP`, it scrolls 5 lines as expected (macOS). Please, check your keyboard layout and terminal to verify if the latter is really receiving the correct keystroke.

**Comment by ronisbr** [comment]
https://asciinema.org/a/moUGJ5m8VVYkD0qrAGuYBJkvR

**Comment by bjarthur** [comment]
indeed, it's a problem with my terminal settings.  iterm2 worked out of the box, but Terminal.app from apple was missing definitions in it's profile, as described here:  https://apple.stackexchange.com/questions/412107/terminal-app-eats-shift-key-when-used-with-up-and-down-arrows-but-not-left-or-r.  like this specifically:

<img width="779" alt="Screenshot 2024-01-11 at 1 56 04 PM" src="https://github.com/ronisbr/TerminalPager.jl/assets/1538268/ec9f4fa4-9f0f-429a-9ebe-36ef73a2ae27">
