### ISSUE TITLE
The `@help` macro does not show the docstrings for macros

### ISSUE THREAD

**Issue by piechologist** [ronisbr/TerminalPager.jl#37]
Example: `@help @info` displays just "#= =#" in the pager, not the docstring for `@info`.

I could track the issue down to the `macro help(f)` definition in `helpers.jl`, line 24. When calling `@help @info` in the REPL, the variable `f_str` is set to something like `#= REPL[21]:1 =# @info`.

I tried 
```Julia
local f_str = chopprefix(string(f), r"#= .+ =# ")
```
which is not elegant but it works fine.

I could make a PR for that or maybe you have a better solution?

**Comment by ronisbr** [comment]
Hi @piechologist !

Sorry for the delay.

I took a look at the issue and I think your proposed solution is a great idea! If you could submit this PR, that would be awesome!

Thanks!

**Comment by piechologist** [comment]
Works as intended in v0.6.0. Thanks for merging!

**Comment by ronisbr** [comment]
Thanks for the fix @piechologist !
