### ISSUE TITLE
TerminalPager doesn't work with Julia 1.11

### ISSUE THREAD

**Issue by matthias314** [ronisbr/TerminalPager.jl#38]
I cannot get the package to work with Julia 1.11:
```
~$ julia --startup-file=no
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.11.1 (2024-10-16)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using TerminalPager
ERROR: InitError: MethodError: no method matching _init_pager_repl_mode(::REPL.LineEditREPL)
The function `_init_pager_repl_mode` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  _init_pager_repl_mode(::REPL.AbstractREPL)
   @ TerminalPager /usr/local/julia-depot/packages/TerminalPager/beP7K/src/repl.jl:168
```
This error message is weird since
```
julia> using REPL; REPL.LineEditREPL <: REPL.AbstractREPL
true
```
With Julia 1.10.5 the package works fine.

**Comment by ronisbr** [comment]
Hi @matthias314 !

Can you describe better your setup? It is working perfectly here.

<img width="912" alt="Screenshot 2024-11-11 at 19 03 22" src="https://github.com/user-attachments/assets/fe9dbedf-659e-4c4a-8433-c6b251b4e7e6">

**Comment by matthias314** [comment]
Yesterday I figured out that it is related to JuliaLang/Julia#56216. I have set `JULIA_DEPOT_PATH`. Unsetting it makes the issue go away. So I believe this issue can be closed as it will probably be fixed in the next minor release of Julia 1.11. Anyway, thanks for responding!

**Comment by nicolamos** [comment]
Hi! I still get this issue. Is there any workaround at the moment?
I went to through the mentioned issue but I could not find any solutions right now.

**Comment by matthias314** [comment]
The solution that works for me (and that is mentioned on some GitHub page for Julia) is to have `JULIA_DEPOT_PATH` end with `:`, as in
```
export JULIA_DEPOT_PATH=/usr/local/julia-depot:
```

**Comment by nicolamos** [comment]
Ok thanks! Defining the depot like you suggested seems to work. I tried that before but it did not work, maybe something was cached.
