### ISSUE TITLE
Change freeze corner case errors

### ISSUE THREAD

**Issue by bkamins** [ronisbr/TerminalPager.jl#9]
steps:
1. press <kbd>f</kbd>
2. press <kbd>Enter</kbd>
3. press <kbd>Enter</kbd>

Result:
```
Freeze columns: ERROR: MethodError: no method matching isless(::Nothing, ::Int64)
Closest candidates are:
  isless(::Any, ::Missing) at missing.jl:88
  isless(::Missing, ::Any) at missing.jl:87
  isless(::AbstractFloat, ::Real) at operators.jl:169
```
you need to handle `nothing` in the input when the user just presses enter (maybe it should be just `something(your_var, 0)` so that <kbd>Enter</kbd> resets freeze to 0?)

**Comment by ronisbr** [comment]
Ooops :) Thanks @bkamins, it should be fixed now.
